language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer update --no-interaction --prefer-dist --prefer-stable

script:
  - ./vendor/bin/phpunit -v

jobs:
  include:
    - stage: Test
      php: 7.0
      name: prefer-lowest
      install:
        - composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
    - name: sentry/sentry dev-develop
      install: composer require sentry/sentry:dev-develop

